services:
  - docker

script:
  - docker build --build-arg TAGSPACES_VERSION="$(curl https://api.github.com/repos/tagspaces/tagspaces/releases/latest --silent | jq .tag_name -r)" . -t "joschi36/tagspaces:$(curl https://api.github.com/repos/tagspaces/tagspaces/releases/latest --silent | jq .tag_name -r)"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "joschi36/tagspaces:$(curl https://api.github.com/repos/tagspaces/tagspaces/releases/latest --silent | jq .tag_name -r)"
