name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Download Tagspaces
      run: 'export TAGSPACES_VERSION=$(curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/tagspaces/tagspaces/releases/latest --silent | jq .tag_name -r)'
    - name: Build the Docker image
      run: docker build --build-arg TAGSPACES_VERSION . -t "joschi36/tagspaces:$(echo $TAGSPACES_VERSION)"
    - name: Docker Login
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - name: Docker Push
      run: docker push "joschi36/tagspaces:$(echo $TAGSPACES_VERSION)"
