name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download Tagspaces
      run: 'export TAGSPACES_VERSION=$(curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/tagspaces/tagspaces/releases/latest --silent | jq .tag_name -r)'
    - name: Build and push to docker hub
      uses: "pangzineng/Github-Action-One-Click-Docker@master"
      secrets:
      - "DOCKER_USERNAME" 
      - "DOCKER_PASSWORD"
      env:
        DOCKER_IMAGE_NAME: joschi36/tagspaces
        DOCKER_IMAGE_VERSION: ${{ TAGSPACES_VERSION }}
